# Generated by Django 5.2.11 on 2026-02-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_machine_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='category',
            field=models.CharField(choices=[('tractor', 'Tractor'), ('harvester', 'Harvester'), ('plough', 'Plough'), ('sprayer', 'Sprayer'), ('seeder', 'Seeder'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
