# Generated by Django 5.2.11 on 2026-02-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_machine_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='machines/'),
        ),
    ]
